import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PageHeader from '@/components/layouts/PageHeader';
import { NextAuthProvider } from './SessionProvider';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextAuthProvider>
      <html lang='ja'>
        <body className={inter.className}>
          <PageHeader />
          <main className='m-auto max-w-7xl p-4'>{children}</main>
          <Toaster />
        </body>
      </html>
    </NextAuthProvider>
  );
}
